apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
###Commands in pods are equal to entrypoint of Docker
    command: ["printenv"]
###Args in pods are equal to Command in Docker 
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure