apiVersion: v1    ## kubernetes API version to be used for mentioned object
kind: Pod      ## Type of object you are creating, in this case it is Pod, other options are deployment/statefulset/replicaset
metadata: 
  name: myfirstpod
  labels:
     owner: yogesh
     tier: web
     costcenter: "12334"
     environment: dev
spec:
  containers: 
  - name: mycontainer
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "sleep 15"]  
