apiVersion: v1
kind: Pod
metadata:
  name: mc2
spec:
  containers:
  - name: producer
    image: allingeek/ch6_ipc
    command: ["/bin/sh","-c"]
    args: ["./ipc -producer"]

  - name: consumer
    image: allingeek/ch6_ipc
    command: ["/bin/sh","-c"]
    args: ["./ipc -consumer"]
  restartPolicy: Never
