apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: webserver
    image: nginx
    volumeMounts:
    - mountPath: /nginxdata
      name: mydir
    - mountPath: /usr/share/nginx/html/index.html
      name: myfile
  volumes:
  - name: mydir
    hostPath:
      # Ensure the file directory is created.
      path: /var/local/nginx
      type: DirectoryOrCreate
  - name: myfile
    hostPath:
      path: /var/local/nginx/custom_nginx.html
      type: FileOrCreate
