apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ExternalName
  externalName: <RDS END Point>

---

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: webusermgmt
  labels:
    app: webusermgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webusermgmt
  template:  
    metadata:
      labels: 
        app: webusermgmt
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: webusermgmt
          image: nitinkansal/usermanagement:1.0 
          ports: 
            - containerPort: 8095           
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "webappdb"            
            - name: DB_USERNAME
              value: "admin"            
            - name: DB_PASSWORD
              value: "Redhat1449"   
          livenessProbe:
            exec:
              command: 
                - /bin/sh
                - -c 
                - nc -z localhost 8095
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /usermgmt/health-status
              port: 8095
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: webusermgmt
  labels: 
    app: webusermgmt
spec:
  type: LoadBalancer
  selector:
    app: webusermgmt
  ports: 
    - port: 8095
      targetPort: 8095



