apiVersion: batch/v1
kind: Job
metadata:
  name: busybox
spec:
#  completions: 4
#  parallelism: 2
  activeDeadlineSeconds: 20
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "50"]
      restartPolicy: Never
