apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
  file1.txt: |  
    This is my special configuration file
    Lets dump this file inside pod
---
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "sleep 100" ]
      volumeMounts:
      - name: vol
        mountPath: /etc/config
  volumes:
    - name: vol
      configMap:
        name: special-config
        defaultMode: 0755  
  restartPolicy: Never